travis:
  secure:
    BINSTAR_TOKEN: Kzv2sywqU4V6FnmU6c/qtLgAHxy7Z+VWfsRTvjADDY2nSutZNtwko2Lk5YnyGryfMEGdBdbLUSS0fTDHT31dPxh5NI2zUFGHFr6o2kmOzIoHSRTaBEoQ9jGViQ/R6i+lyu05WKSfMLTJy0cRGpmo+Rg4p1LhBRp9uCbEv7bMLNwEj2b5PMYV3hpBypfdItt8btMQG58/OzHvtoYyjbp4X8pT2QhQOIx7gunMsXgUBiWLw2r/5DpYSgYTbZAPYOVEpagKzKu9cf0d6Q5wiAxxVjMYiEE00uChlB795iLWHwwuv7566Z3uF7ESwg8obmJIsqyX1mckOg82JYTsGMtAKDE/u9qpy5FHHWgEPiTVAG5a3Ez48CeE3BzBfjGRNeqhh77/nzqQduBMSItnUaXuUL90jfXPQFx4QWLRi6eTrvd/emy0jeDsY/2No+8Ydfw7T5CRoVUZFgd0Er/xHJnZDDQ1c2zkP1LKxU0z8SsBAOg/Lv+AZyz+CIA9muAWxXdhpoKBEAuMrE3W8pgyqvoll11JsVX5FORkfSKfOC1Cw/3AsWfcnTwcLfe8vzTv16Si+tuTwpJZypDVDvI1bMuPt97+UC7l+u1MwQSaXRuzaxdUvTAN1/CZc1pAoVpoXg2IHwIK6ZZizwZXHmADCAphzxbw8Irw+g4Za0drtFNnkYk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
